services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce
      - JWT_SECRET_KEY deb4fbb4f3bfcbbf602e72ed176f89c32c21e7801287e8543c1bda89ab86b37c53543d30ed3a2e918b7b58ed88719ae9702a2aaf3835de735490e22de935b5a5
      - JWT_REFRESH_SECRET_KEY ae896022398effbb041564fa9fac7445b4050910cc380236d2c342870efdc1a80f9d984ee38b13e6d284bdfd994a0dca509e5e7c7971e73434841b672bb56f78
      - JWT_EXPIRY_TIME 1h
      - JWT_REFRESH_EXPIRE_TIME 7d
    volumes:
      - ecommerce_db:/var/lib/ecommerce-db
    develop:
      watch:
        - action: sync
          path: ./web
          target: /src/web
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  postgres:
    image: postgres:15
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - ecommerce_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  ecommerce_db: